version: '3'
services:
  php:
    build: build/php
    expose:
      - '9000'
    links:
      - db
    volumes:
      - ./:/var/www/html/symfony:cached
      - ./logs:/var/log

  web:
    build: build/nginx
    ports:
        - '80:80'
    links:
        - php
        - db
    volumes:
        - ./:/var/www/html/symfony:cached
        - ./logs:/var/log/nginx
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
      image: adminer:4.6.3-standalone
      container_name: tgv-adminer
      restart: always
      depends_on:
        - db
      ports:
        - '8084:8080'
      environment:
        - 'ADMINER_DESIGN=pappu687'
